### ISSUE TITLE
Hi buddy! amazing script can you add the followning?

### ISSUE THREAD

**Issue by ChrisBomBom** [MRegirouard/OpenSeaScripts#1]
is there a chance we can add the duration button? 

div[id='tippy-119']" is dynamic and i cant figure out how to handle it !

**Comment by MRegirouard** [comment]
Hi @ChrisBomBom,

Thanks for expressing interest in this project.

I assume by the "duration button" you are referring to the setting to customize the start and end date and time that the auction is available for when listing for sale.

I have not yet implemented the listing for sale feature, only uploading so far. However, if you are going to use this I would be happy to look into it.

**Comment by MRegirouard** [comment]
@ChrisBomBom ,

I have just finished writing the `sell_asset` function, but I have not added the functionality of setting a duration yet. I should be able to finish this by the end of the day today or tomorrow.

**Comment by MRegirouard** [comment]
@ChrisBomBom,

Your requested functionality has been added! OpenSea's date entry method is quite poorly designed in my opinion and this was difficult to overcome in the programming. However, it still may not work well so I suggest you keep an eye on it or at least test it out with some dates. Here are a few things to keep in mind:
- Start dates must be in the future, but no more than 30 days in the future.
- End dates must be past the start date, but no more than 6 months past the start date.
- My script does not check the dates you give it at all, but they will fail on OpenSea. The `sell_asset` function will return `False` in this case.
- Sometimes, the date selector gets "stuck" on a previous date entered. It's really inconsistent but changing the date on the calendar below the input fields sometimes helps.
- This may not work for all localities. I have no idea if OpenSea changes the date input order or not, but my script assumes that OpenSea uses MM/DD/YY as we do in the US.
- This may not work when dates are in a different year than right now. Because I can't schedule a date more than 6 months into the future, I am unable to test the year entry. OpenSea doesn't let me edit the year field as it is currently January and the next year is more than the maximum of 6 months away. My script does not do anything with the year value you give it, but there's a chance OpenSea figures it out automatically.

Please use this with caution in general. Let me know how it goes or if there are issues. I hope this feature is helpful to you.

**Comment by ChrisBomBom** [comment]
> @ChrisBomBom,
> 
> Your requested functionality has been added! OpenSea's date entry method is quite poorly designed in my opinion and this was difficult to overcome in the programming. However, it still may not work well so I suggest you keep an eye on it or at least test it out with some dates. Here are a few things to keep in mind:
> 
> * Start dates must be in the future, but no more than 30 days in the future.
> * End dates must be past the start date, but no more than 6 months past the start date.
> * My script does not check the dates you give it at all, but they will fail on OpenSea. The `sell_asset` function will return `False` in this case.
> * Sometimes, the date selector gets "stuck" on a previous date entered. It's really inconsistent but changing the date on the calendar below the input fields sometimes helps.
> * This may not work for all localities. I have no idea if OpenSea changes the date input order or not, but my script assumes that OpenSea uses MM/DD/YY as we do in the US.
> * This may not work when dates are in a different year than right now. Because I can't schedule a date more than 6 months into the future, I am unable to test the year entry. OpenSea doesn't let me edit the year field as it is currently January and the next year is more than the maximum of 6 months away. My script does not do anything with the year value you give it, but there's a chance OpenSea figures it out automatically.
> 
> Please use this with caution in general. Let me know how it goes or if there are issues. I hope this feature is helpful to you.

Thank you very much !! i will check it out! i agree! poorly designed ! i tried to add the function on a python script but i failed evrey time
